USER_NAME := antiheadshot

#CONSOLE_ENABLE = yes

BOOTMAGIC_ENABLE = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
SWAP_HANDS_ENABLE = yes

RGBLIGHT_ENABLE = yes

UNICODE_ENABLE = no
LTO_ENABLE = yes